#!/usr/bin/env bash
# Corpus health check. Run from anywhere: bash corpus/lint.sh [--index]
#
#   (no args)  check frontmatter, link resolution, page size, stale path roots.
#              Exits non-zero on any finding, so it can gate a commit.
#   --index    regenerate the catalog block in index.md from each wiki page's
#              `summary:` frontmatter. Never hand-maintain that block.

set -uo pipefail

CORPUS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$CORPUS/.." && pwd)"
MAX_BODY_LINES=200

# Path roots the repo has abandoned. A corpus page still pointing at one of
# these is stale by definition. Add a root here when you retire a directory.
ABANDONED_ROOTS=(
  # Empty on purpose: this repo starts at the corpus and has retired nothing.
  # Add a root here the day a directory is abandoned, so any page still pointing
  # at it fails this check.
)

fail=0
note() { printf '  %s\n' "$1"; fail=1; }

# Body lines = everything after a leading `---` frontmatter block.
body_start() {
  if [ "$(head -1 "$1")" = "---" ]; then
    awk 'NR>1 && /^---$/ {print NR+1; exit}' "$1"
  else
    echo 1
  fi
}

# Read one frontmatter key. Empty if absent.
fm_get() {
  awk -v k="$2" '
    NR==1 && $0!="---" {exit}
    NR>1 && /^---$/ {exit}
    NR>1 {
      key=$0; sub(/:.*/,"",key)
      if (key==k) { sub(/^[^:]*:[[:space:]]*/,""); print; exit }
    }' "$1"
}

# ---------------------------------------------------------------- --index
if [ "${1:-}" = "--index" ]; then
  tmp="$(mktemp)"
  {
    echo "<!-- catalog:start — generated by lint.sh --index, do not hand-edit -->"
    echo
    echo "| Page | What it answers |"
    echo "|---|---|"
    for f in "$CORPUS"/wiki/*.md; do
      [ -e "$f" ] || continue
      base="$(basename "$f")"
      summary="$(fm_get "$f" summary)"
      [ -n "$summary" ] || summary="**MISSING \`summary:\`**"
      printf '| [%s](wiki/%s) | %s |\n' "$base" "$base" "$summary"
    done
    echo
    echo "<!-- catalog:end -->"
  } > "$tmp"

  if grep -q '^<!-- catalog:start' "$CORPUS/index.md" 2>/dev/null; then
    awk -v repl="$tmp" '
      /^<!-- catalog:start/ { while ((getline line < repl) > 0) print line; skip=1; next }
      /^<!-- catalog:end/   { skip=0; next }
      !skip
    ' "$CORPUS/index.md" > "$CORPUS/index.md.new" && mv "$CORPUS/index.md.new" "$CORPUS/index.md"
  else
    cat "$tmp" >> "$CORPUS/index.md"
  fi
  rm -f "$tmp"
  echo "index.md catalog regenerated from $(ls "$CORPUS"/wiki/*.md | wc -l) wiki pages."
  exit 0
fi

# ------------------------------------------------------- 1. wiki frontmatter
echo "frontmatter (wiki/)"
for f in "$CORPUS"/wiki/*.md; do
  [ -e "$f" ] || continue
  rel="${f#$REPO/}"
  [ -n "$(fm_get "$f" summary)" ] || note "$rel — missing 'summary:'"
  updated="$(fm_get "$f" updated)"
  if [ -z "$updated" ]; then
    note "$rel — missing 'updated:'"
  elif ! printf '%s' "$updated" | grep -qE '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'; then
    note "$rel — 'updated: $updated' is not YYYY-MM-DD"
  fi
done

# ------------------------------------------------------------ 2. page size
echo "page size (max $MAX_BODY_LINES body lines)"
for f in "$CORPUS"/wiki/*.md; do
  [ -e "$f" ] || continue
  rel="${f#$REPO/}"
  start="$(body_start "$f")"
  total="$(wc -l < "$f")"
  body=$(( total - start + 1 ))
  [ "$body" -le "$MAX_BODY_LINES" ] || \
    note "$rel — $body body lines, over $MAX_BODY_LINES. Split it and cross-link."
done

# -------------------------------------------------------- 3. relative links
echo "relative links"
while IFS= read -r f; do
  rel="${f#$REPO/}"
  dir="$(dirname "$f")"
  grep -oE '\]\([^)]+\)' "$f" | sed 's/^](//; s/)$//' | while IFS= read -r target; do
    case "$target" in
      http://*|https://*|mailto:*|\#*) continue ;;
    esac
    target="${target%%#*}"
    [ -n "$target" ] || continue
    case "$target" in
      /*) probe="$REPO$target" ;;
      *)  probe="$dir/$target" ;;
    esac
    [ -e "$probe" ] || echo "  $rel — broken link: $target"
  done
done < <(find "$CORPUS" -name '*.md') > /tmp/corpus-links.$$ 2>/dev/null
if [ -s /tmp/corpus-links.$$ ]; then cat /tmp/corpus-links.$$; fail=1; fi
rm -f /tmp/corpus-links.$$

# --------------------------------------------------------- 4. stale roots
echo "stale path roots"
for root in ${ABANDONED_ROOTS[@]+"${ABANDONED_ROOTS[@]}"}; do
  while IFS= read -r hit; do
    f="${hit%%:*}"
    # log.md is an append-only historical record — old paths there are correct,
    # as are immutable briefs. A line may also opt out with <!-- lint-ok -->
    # when it deliberately names a retired path (e.g. recording its retirement).
    case "$f" in */log.md|*/briefs/done/*|*/briefs/superseded/*) continue ;; esac
    case "$hit" in *'<!-- lint-ok -->'*) continue ;; esac
    note "${f#$REPO/} — references abandoned path root '$root'"
  done < <(grep -rn --include='*.md' -F "$root" "$CORPUS" 2>/dev/null)
done

echo
if [ "$fail" -eq 0 ]; then
  echo "corpus lint: clean"
else
  echo "corpus lint: findings above"
fi
exit "$fail"
