import type Database from "better-sqlite3";

import { recordActorAudit, type AuditActor } from "../audit.js";
import { grantTargetId } from "../db/audit-log.js";
import {
  ensureGrant,
  listGrantsForSubject,
  revokeAppAccess as revokeAppAccessRows,
  revokeGrant,
  SUPERUSER_ACTOR,
  type GrantRow,
} from "../db/grants.js";

/**
 * The **write** side of `(subject, app, role)` — issuing and removing grants,
 * each paired with its audit row in one transaction.
 *
 * `grants/resolve.ts` is the read side (brief 04): what an app asks about a
 * subject on every request. The split is not tidiness. A read is a hot path that
 * may be cached; a write is rare, must be recorded, and is the only thing in
 * Ward that changes what anyone can reach. Nothing in this file answers a
 * question, and nothing in `resolve.ts` changes an answer.
 *
 * ## Role strings are opaque here, exactly as everywhere else
 *
 * No function below looks at the *value* of a role. It is stored, echoed back
 * and deleted; what `admin` means is prm's business, and the moment Ward learns
 * it, adding a capability to any of six apps means redeploying the identity
 * service (`corpus/wiki/decisions-accounts.md`). The one consequence worth
 * naming: a role may contain `:`, which is why every audit row here builds its
 * `target_id` with `grantTargetId` rather than by string concatenation.
 *
 * ## There is no wildcard
 *
 * There is no `addGrantForEveryApp`, and there should not be. Even the owner
 * account holds one explicit row per app, so a newly-added app is reachable by
 * nobody until someone says otherwise — the same fails-safe property the
 * per-app registration flag exists for (`corpus/wiki/decisions-admin.md`).
 *
 * ## Idempotence is a property of the surface, not of the caller
 *
 * Adding a role somebody already holds and removing one they never had are both
 * **successes**. `db/grants.ts` gives that for free through
 * `ON CONFLICT DO NOTHING` and a `DELETE` that matches nothing, so there is no
 * check-then-write gap to race — two console clicks arriving together cannot
 * produce two rows or two audit entries.
 *
 * **A no-op writes no audit row.** The log records changes of authority; a
 * double-click changed none, and auditing it would bury the rows an operator
 * actually needs under noise they generated by mis-clicking. Every return value
 * below says plainly whether anything happened.
 */

/** Who a grant is recorded as coming from, derived rather than passed twice. */
function grantedByFor(actor: AuditActor): string {
  /**
   * `grants.granted_by` is `NOT NULL` and deliberately un-defaulted in
   * `db/grants.ts`: a grant that cannot say who issued it fails to answer the
   * one question it is stored for. Deriving it from the audit actor means the
   * column and the log cannot disagree, which they could if a route passed each
   * of them separately.
   *
   * The console is the `superuser` branch and stores the `SUPERUSER_ACTOR`
   * sentinel — not a subject, and deliberately not resolvable to one, because
   * the break-glass credential has no `users` row. An owner account issuing
   * grants through some later surface is the `account` branch and stores its own
   * subject.
   */
  return actor.actorKind === "account" && actor.actorSubject !== null
    ? (actor.actorSubject ?? SUPERUSER_ACTOR)
    : SUPERUSER_ACTOR;
}

export interface GrantTriple {
  subject: string;
  appSlug: string;
  role: string;
}

export interface AddGrantResult {
  /**
   * The stored row, whether this call created it or found it already there — so
   * a caller can echo the grant back without a second read.
   */
  grant: GrantRow;
  /** False when the person already held this role. Still a success. */
  created: boolean;
}

/**
 * Issue one grant, or confirm the one that is already there.
 *
 * Throws `SqliteError` with `SQLITE_CONSTRAINT_FOREIGNKEY` for a subject or slug
 * that does not exist — real foreign keys, enforced because `openDatabase` sets
 * `foreign_keys = ON`. Routes check first for a clean 404 and still catch this,
 * because between the check and the insert an app can be deleted.
 */
export function addGrant(
  db: Database.Database,
  actor: AuditActor,
  input: GrantTriple,
): AddGrantResult {
  const grantedBy = grantedByFor(actor);

  return db.transaction((): AddGrantResult => {
    const inserted = ensureGrant(db, { ...input, grantedBy });

    if (inserted === undefined) {
      // Already held. Read the row back so the caller's response shape does not
      // depend on which branch it took — `granted_at` and `granted_by` belong to
      // the original grant, not to this attempt, and that is the honest answer.
      const existing = listGrantsForSubject(db, input.subject).find(
        (row) => row.app_slug === input.appSlug && row.role === input.role,
      );
      // Unreachable: `ensureGrant` returned undefined only because the row is
      // there, and we are inside the same transaction that observed it.
      if (existing === undefined) {
        throw new Error("grant vanished between insert and read");
      }
      return { grant: existing, created: false };
    }

    recordActorAudit(db, actor, {
      action: "grant.create",
      targetKind: "grant",
      targetId: grantTargetId(input.subject, input.appSlug, input.role),
      detail: { subject: input.subject, appSlug: input.appSlug, role: input.role },
    });

    return { grant: inserted, created: true };
  })();
}

export interface RemoveGrantResult {
  /** False when they did not hold it. Still a success; no audit row. */
  removed: boolean;
}

/** Remove one role. Removing a role nobody holds is not an error. */
export function removeGrant(
  db: Database.Database,
  actor: AuditActor,
  input: GrantTriple,
): RemoveGrantResult {
  return db.transaction((): RemoveGrantResult => {
    if (!revokeGrant(db, input.subject, input.appSlug, input.role)) {
      return { removed: false };
    }

    recordActorAudit(db, actor, {
      action: "grant.revoke",
      targetKind: "grant",
      targetId: grantTargetId(input.subject, input.appSlug, input.role),
      detail: { subject: input.subject, appSlug: input.appSlug, role: input.role },
    });

    return { removed: true };
  })();
}

export interface RemoveAppAccessResult {
  /** How many rows went. Zero means they had no access to that app already. */
  removed: number;
  /** The roles that were removed, for the audit row and the response. */
  roles: string[];
}

/**
 * Remove every role one person holds in one app — "revoke access", as opposed to
 * "remove this one role".
 *
 * One audit row rather than one per role, with the roles listed in `detail`: the
 * operator performed one act, and splitting it into N rows would make a person
 * with three roles look like three separate decisions. `target_kind` is the app
 * here, because the triple no longer identifies what happened.
 */
export function removeAppAccess(
  db: Database.Database,
  actor: AuditActor,
  input: { subject: string; appSlug: string },
): RemoveAppAccessResult {
  return db.transaction((): RemoveAppAccessResult => {
    // Read before deleting: the roles are gone afterwards, and they are the
    // only interesting content of the audit row.
    const roles = listGrantsForSubject(db, input.subject)
      .filter((row) => row.app_slug === input.appSlug)
      .map((row) => row.role);

    const removed = revokeAppAccessRows(db, input.subject, input.appSlug);
    if (removed === 0) {
      return { removed: 0, roles: [] };
    }

    recordActorAudit(db, actor, {
      action: "grant.revoke_app",
      targetKind: "app",
      targetId: input.appSlug,
      detail: { subject: input.subject, appSlug: input.appSlug, roles },
    });

    return { removed, roles };
  })();
}
